DROP TABLE IF EXISTS clients;

CREATE TABLE clients(
  ID BIGSERIAL NOT NULL,
  NAME TEXT NOT NULL ,
  SURNAME TEXT NOT NULL,
  NIP TEXT NOT NULL
);

DROP TABLE IF EXISTS parts;

CREATE TABLE parts(
  ID BIGSERIAL NOT NULL ,
  PART_NAME TEXT NOT NULL,
  PART_NUMBER TEXT NOT NULL ,
  price_wholesale FLOAT,
  price_retail FLOAT
);





